// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DaysTemplateController from "./days_template_controller"
application.register("days-template", DaysTemplateController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import FlipcardController from "./flipcard_controller"
application.register("flipcard", FlipcardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import PortionsController from "./portions_controller"
application.register("portions", PortionsController)

import PreferencesController from "./preferences_controller"
application.register("preferences", PreferencesController)

import ShoppingListController from "./shopping_list_controller"
application.register("shopping-list", ShoppingListController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import WeekLoadingController from "./week_loading_controller"
application.register("week-loading", WeekLoadingController)

import WeekSelectController from "./week_select_controller"
application.register("week-select", WeekSelectController)
